### ISSUE TITLE
Components are unresponsive in environments where pointer events are not supported

### ISSUE THREAD

**Issue by g-hor** [Wondermarin/react-color-palette#78] opened 2024-07-23 17:39 UTC
### My Environment
I am currently developing in a browser environment that doesn't support pointer events. 

| Dependency                  | Version  |
| --------------------------- | -------- |
| ts-node version                    | v10.9.1   |
| react-color-palette version | v7.1.0     |

### Expected Behavior:
As a user, I should be able to click and drag across any of the color palette components to update a color value.

### Actual Behavior:
The color palette components do not seem to register any events from any click or drag actions. The color value remains unchanged, and the color cursor remains at the same position of its initial state.

### Additional Context:
My development environment is quite niche, as I am creating a plugin for Adobe Illustrator. I'll include some more context in case it's helpful for debugging purposes:

In Illustrator, plugins use [CEP 11](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md), which is based on a version of Chromium (v.88) that actually does support pointer events. However, there is a known issue with CEP where pointer events are not fired correctly on MacOS. This has been an issue for years, and it seems a fix will not be implemented anytime in the foreseeable future.

**Comment by Wondermarin** [comment] 2024-07-23 19:04
The problem indeed seems very niche. I can try to fix it, and the solution I see for now is to completely avoid `pointer` events in the CEP environment. However, since I've never worked in this environment before, it might take more time to implement.

**Comment by g-hor** [comment] 2024-07-23 20:43
@Wondermarin Thanks for your quick response! Although my development environment is probably the edgiest of edge cases, I would like to note that this issue may still be relevant in [other environments/browsers where `pointer` events aren't necessarily supported](https://caniuse.com/?search=PointerEvent).

**Comment by Wondermarin** [comment] 2024-07-23 21:32
Yes, potentially such an issue might arise in older environments; however, I believe that having 96%+ support is sufficient to rely on this API. I aim to support environments that were released after Chromium 77, and since your environment is based on Chromium 88, and the issue is a specific case, support for it will be added.

**Comment by g-hor** [comment] 2024-07-23 21:41
Awesome, thanks for hearing me out. I understand this is low priority, but feel free to reach out to me if you'd like any more details (I have notifications enabled for this Issue). Looking forward to your fix!

**Comment by Wondermarin** [comment] 2024-07-30 11:32
Please check v7.2.2. If the issue has been resolved in this version, I'll go ahead and close it.

**Comment by g-hor** [comment] 2024-08-02 14:44
Please don't take this the wrong way, but I want to give you a big big hug. Thank you so much for your super quick response!!! You're amazing!

**Closed** 2024-08-02 20:31 UTC
Labels: p: low, s: in progress, semver: minor, t: bug
