### ISSUE TITLE
 It's a bit inconvenient to use useColor with forms

### ISSUE THREAD

**Issue by dieptv1999** [Wondermarin/react-color-palette#76] opened 2024-07-06 03:24 UTC

**Comment by Wondermarin** [comment] 2024-07-12 13:12
Could you please provide more information? What exactly are you having trouble with, and could you share a link to an example where this issue can be reproduced?

**Comment by datnd99** [comment] 2024-07-16 15:30
> Could you please provide more information? What exactly are you having trouble with, and could you share a link to an example where this issue can be reproduced?

This is not a fix request. It seems he needs a advanced function that allows control of the color-picker instead of using useColors.

**Comment by aleskinmk** [comment] 2024-07-28 12:18
I think he meant that there is no way to control color by setting it without useColor hook. 

Actuality there is a way. You can update the state of color with ColorService utilite:

`
import { ColorService } from "react-color-palette"

const [color, setColor] = useColor("#000000");
setColor(ColorService.convert("hex", "#000000"));

`

**Comment by Wondermarin** [comment] 2024-09-10 02:51
I'm closing this issue since no additional context has been provided. If you need more control over color conversion, you can use `ColorService`, as @mkalesk mentioned. If anyone has a clear vision of how this should be implemented, feel free to create a PR or open a new issue with a detailed description of the desired behavior.

**Closed by Wondermarin** 2024-09-10 02:51 UTC
Labels: t: enhancement
